//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuildProject()
        {
            this.PublishedProjects = new HashSet<PublishedProject>();
        }
    
        public int Build_Id { get; set; }
        public int Proj_Id { get; set; }
        public int E_Id { get; set; }
        public string URL { get; set; }
        public string Version { get; set; }
        public System.DateTime BuidDate { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublishedProject> PublishedProjects { get; set; }
    }
}
