//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseProject
    {
        public int Release_Id { get; set; }
        public int Publish_Id { get; set; }
        public int R_Id { get; set; }
        public System.DateTime ReleaseDate { get; set; }
    
        public virtual PublishedProject PublishedProject { get; set; }
        public virtual ReleaseManager ReleaseManager { get; set; }
    }
}
